/**
 * Customer QR table page — UI strings (ar / tr / en).
 * Loaded inline in index.html; language from API guestLanguage.
 */
(function (global) {
  var PACK = {
    ar: {
      pageTitle: "طلب من الطاولة — ZEKiQ",
      loadingTitle: "جاري تحميل المينو…",
      loadingSub: "صفحات الكتاب الحقيقي",
      menuList: "📋 القائمة",
      send: "إرسال ✓",
      guide1: '<span class="guide-n">1</span> اضغط <strong>+</strong> الأخضر على الصورة',
      guide2: '<span class="guide-n">2</span> ثم <strong>إرسال</strong> للتأكيد',
      coachTitle: "كيف تطلب؟",
      coverWelcomeGreet: "أهلاً بك",
      coverWelcomeSub: "حرصاً على راحتك — لأن راحتك تهمنا",
      coverOrderHead: "اطلب بنفسك بسهولة — والطلب سيصل إلى طاولتك",
      coverOrderLead: "٤ خطوات بسيطة من هاتفك إلى طاولتك",
      coverWelcomeHead: "أهلاً بك",
      coverWelcomeLead: "حرصاً على راحتك — لأن راحتك تهمنا",
      coverPitch1: "نقدّم بين يديك تحكّماً كاملاً بطلباتك",
      coverPitch2: "تصفّح المينو بحرية وأرسل طلبك مباشرة للمطبخ",
      coverPitch3: "أضف ملاحظاتك لكل صنف — كما تحب بالضبط",
      coach1: 'تصفّح <strong>المينو</strong> — اسحب يميناً/يساراً على الصورة أو استخدم <strong>السابق / التالي</strong>',
      coach2: 'اضغط <strong>+ الأخضر</strong> على الصورة لإضافة طعام',
      coach3: 'اضغط <strong>إرسال</strong> في الأعلى → راجع السلة → <strong>تأكيد وإرسال</strong>',
      coach4: 'ضع <strong>ملاحظتك</strong> على الطلب — مثلاً إذا رغبت في إزالة أو إضافة شيء',
      coachOk: "فهمت — ابدأ الطلب ✓",
      coverStartBadge: "الغلاف",
      coverStartTitle: "Tonino Coffee",
      coverStartSub: "اضغط «فهمت» لبدء الطلب",
      coverEndBadge: "نهاية المينو",
      coverEndTitle: "انتهى المينو",
      coverEndSub: "اسحب للخلف أو أرسل طلبك من الأعلى",
      prev: "◀ السابق",
      next: "التالي ▶",
      swipeHint: "اسحب لقلب الصفحة",
      fsHint: "👆 اضغط على المينو لملء الشاشة",
      menuTitle: "📋 قائمة الأطباق",
      menuSub: "ابحث واطلب من أي صفحة",
      menuSearch: "ابحث… Türk kahve, menemen, pasta…",
      cartTitle: "راجع طلبك",
      cartSub: "عدّل الكمية وأضف ملاحظة تحت كل صنف",
      cartTotal: "المجموع",
      cartSend: "✓ تأكيد وإرسال للمطبخ",
      cartClearAll: "مسح السلة بالكامل",
      cartDelete: "حذف",
      toastCleared: "تم مسح السلة",
      notePh: "ملاحظة عامة للطلب (اختياري)…",
      itemNotePh: "ملاحظة لهذا الصنف (بدون بصل، نصف محمص…)",
      popupClose: "إلغاء",
      popupAdd: "أضف للسلة",
      okTitle: "شكراً! ✓",
      againBtn: "طلب إضافي",
      table: "طاولة",
      items: "أصناف",
      orderTotal: "المجموع",
      emptyCart: "السلة فارغة",
      emptyCartHint: "اضغط + في المينو أو القائمة",
      menuLoading: "جاري تحميل الأطباق…",
      menuNoResults: "لا نتائج",
      errScanQr: "امسح QR",
      errScanQrD: "امسح رمز QR من الطاولة للطلب.",
      errOldQr: "QR قديم",
      errOldQrD: "حدّث الرموز من إعدادات الكاشير.",
      errDisabled: "طلبات QR معطّلة",
      errDisabledD: "فعّلها من إعدادات الكاشير.",
      errConn: "تعذّر الاتصال",
      errConnD: "تأكد أن ZEKiQ POS شغّال و shop.zekiqmenu.com متصل.",
      errTable: "الطاولة غير مفتوحة على الكاشير.\nافتح الطاولة من ZEKiQ POS ثم أعد الإرسال.",
      errToken: "رمز QR قديم — اطبع QR جديد من إعدادات الكاشير.",
      errSend: "تعذّر الإرسال — تحقق من الإنترنت أو أن ZEKiQ POS شغّال.",
      errNet: "تعذّر الاتصال — تحقق من الإنترنت.",
      okDetail: "وصل طلبك إلى الكاشير والمطبخ",
      toastAdded: "→ السلة",
      menuNotReady: "المينو غير جاهز",
      menuNotReadyD: "من الكاشير: استورد PDF المينو ثم شغّل export-guest-menu-book",
    },
    tr: {
      pageTitle: "Masadan sipariş — ZEKiQ",
      loadingTitle: "Menü yükleniyor…",
      loadingSub: "Dijital menü kitabı",
      menuList: "📋 Menü",
      send: "Gönder ✓",
      guide1: '<span class="guide-n">1</span> Resimdeki yeşil <strong>+</strong> düğmesine basın',
      guide2: '<span class="guide-n">2</span> Sonra onay için <strong>Gönder</strong>',
      coachTitle: "Nasıl sipariş verilir?",
      coach1: '<strong>Menüde</strong> gezinin — resimde sağa/sola kaydırın veya <strong>Önceki / Sonraki</strong>',
      coach2: 'Yemek eklemek için resimdeki <strong>yeşil +</strong> düğmesine basın',
      coach3: 'Üstte <strong>Gönder</strong> → sepeti kontrol et → <strong>Onayla</strong>',
      coach4: 'Göndermeden önce her ürünün altına <strong>açık bir not</strong> yazabilirsiniz',
      coachOk: "Anladım — siparişe başla ✓",
      coverStartBadge: "Kapak",
      coverStartTitle: "Tonino Coffee",
      coverStartSub: "Kaydırarak aç →",
      coverEndBadge: "Menü sonu",
      coverEndTitle: "Menü bitti",
      coverEndSub: "Geri kaydırın veya üstten sipariş gönderin",
      prev: "◀ Önceki",
      next: "Sonraki ▶",
      swipeHint: "Sayfayı çevirmek için kaydır",
      fsHint: "👆 Tam ekran için menüye dokunun",
      menuTitle: "📋 Yemek listesi",
      menuSub: "Ara ve her sayfadan sipariş ver",
      menuSearch: "Ara… Türk kahve, menemen, pasta…",
      cartTitle: "Siparişini kontrol et",
      cartSub: "Miktarı düzenle, her ürünün altına not yaz",
      cartTotal: "Toplam",
      cartSend: "✓ Onayla ve mutfağa gönder",
      cartClearAll: "Sepeti temizle",
      cartDelete: "Sil",
      toastCleared: "Sepet temizlendi",
      notePh: "Genel sipariş notu (isteğe bağlı)…",
      itemNotePh: "Bu ürün için not (soğansız, az pişmiş…)",
      popupClose: "İptal",
      popupAdd: "Sepete ekle",
      okTitle: "Teşekkürler! ✓",
      againBtn: "Ek sipariş",
      table: "Masa",
      items: "ürün",
      orderTotal: "Toplam",
      emptyCart: "Sepet boş",
      emptyCartHint: "Menüde + veya listeden ekle",
      menuLoading: "Yemekler yükleniyor…",
      menuNoResults: "Sonuç yok",
      errScanQr: "QR okut",
      errScanQrD: "Sipariş için masadaki QR kodu okutun.",
      errOldQr: "Eski QR",
      errOldQrD: "Kasiyer ayarlarından QR kodlarını güncelleyin.",
      errDisabled: "QR sipariş kapalı",
      errDisabledD: "Kasiyer ayarlarından etkinleştirin.",
      errConn: "Bağlantı hatası",
      errConnD: "ZEKiQ POS açık mı ve internet bağlantısı var mı kontrol edin.",
      errTable: "Masa kasada açık değil.\nZEKiQ POS'tan masayı açın ve tekrar deneyin.",
      errToken: "Eski QR — kasiyerden yeni QR yazdırın.",
      errSend: "Gönderilemedi — internet veya ZEKiQ POS'u kontrol edin.",
      errNet: "Bağlantı hatası — interneti kontrol edin.",
      okDetail: "Siparişiniz kasa ve mutfağa ulaştı",
      toastAdded: "→ sepet",
      menuNotReady: "Menü hazır değil",
      menuNotReadyD: "Kasadan PDF menüyü içe aktarın",
    },
    en: {
      pageTitle: "Table order — ZEKiQ",
      loadingTitle: "Loading menu…",
      loadingSub: "Digital menu book",
      menuList: "📋 Menu",
      send: "Send ✓",
      guide1: '<span class="guide-n">1</span> Tap the green <strong>+</strong> on the image',
      guide2: '<span class="guide-n">2</span> Then <strong>Send</strong> to confirm',
      coachTitle: "How to order?",
      coach1: 'Browse the <strong>menu</strong> — swipe left/right on the image or use <strong>Prev / Next</strong>',
      coach2: 'Tap the green <strong>+</strong> on the image to add food',
      coach3: 'Tap <strong>Send</strong> at top → review cart → <strong>Confirm</strong>',
      coach4: 'In the cart, add a <strong>clear note</strong> under each item before sending',
      coachOk: "Got it — start ordering ✓",
      coverStartBadge: "Cover",
      coverStartTitle: "Tonino Coffee",
      coverStartSub: "Swipe to open →",
      coverEndBadge: "Menu end",
      coverEndTitle: "End of menu",
      coverEndSub: "Swipe back or send your order above",
      prev: "◀ Prev",
      next: "Next ▶",
      swipeHint: "Swipe to turn the page",
      fsHint: "👆 Tap the menu for full screen",
      menuTitle: "📋 Dish list",
      menuSub: "Search and order from any page",
      menuSearch: "Search… coffee, pasta…",
      cartTitle: "Review your order",
      cartSub: "Edit qty and add a note under each item",
      cartTotal: "Total",
      cartSend: "✓ Confirm & send to kitchen",
      cartClearAll: "Clear cart",
      cartDelete: "Delete",
      toastCleared: "Cart cleared",
      notePh: "General order note (optional)…",
      itemNotePh: "Note for this item (no onion, medium rare…)",
      popupClose: "Cancel",
      popupAdd: "Add to cart",
      okTitle: "Thank you! ✓",
      againBtn: "Order more",
      table: "Table",
      items: "items",
      orderTotal: "Total",
      emptyCart: "Cart is empty",
      emptyCartHint: "Tap + on menu or use list",
      menuLoading: "Loading dishes…",
      menuNoResults: "No results",
      errScanQr: "Scan QR",
      errScanQrD: "Scan the table QR code to order.",
      errOldQr: "Old QR",
      errOldQrD: "Update QR codes from cashier settings.",
      errDisabled: "QR orders disabled",
      errDisabledD: "Enable in cashier settings.",
      errConn: "Connection failed",
      errConnD: "Check ZEKiQ POS is running and online.",
      errTable: "Table not open on cashier.\nOpen the table in ZEKiQ POS and try again.",
      errToken: "Old QR — print a new one from cashier.",
      errSend: "Could not send — check internet or ZEKiQ POS.",
      errNet: "Connection failed — check internet.",
      okDetail: "Your order reached the cashier and kitchen",
      toastAdded: "→ cart",
      menuNotReady: "Menu not ready",
      menuNotReadyD: "Import PDF menu from cashier",
    },
  };

  var lang = "ar";

  function t(key) {
    var bag = PACK[lang] || PACK.ar;
    return bag[key] || PACK.ar[key] || key;
  }

  function apply(langCode) {
    lang = langCode === "tr" || langCode === "en" ? langCode : "ar";
    global.__zekiqGuestLang = lang;
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.title = t("pageTitle");
    var htmlIds = {
      "i18n-load-title": "loadingTitle",
      "i18n-load-sub": "loadingSub",
      "i18n-sceneMenuBtn": "menuList",
      "i18n-sceneSendBtn": "send",
      "i18n-guide1": "guide1",
      "i18n-guide2": "guide2",
      "i18n-coach-title": "coachTitle",
      "i18n-coach-1": "coach1",
      "i18n-coach-2": "coach2",
      "i18n-coach-3": "coach3",
      "i18n-coach-4": "coach4",
      "coachOk": "coachOk",
      "i18n-prev": "prev",
      "i18n-next": "next",
      "i18n-swipeHint": "swipeHint",
      "i18n-fsHint": "fsHint",
      "i18n-menu-title": "menuTitle",
      "i18n-menu-sub": "menuSub",
      "i18n-cart-title": "cartTitle",
      "i18n-cart-sub": "cartSub",
      "i18n-cart-total-label": "cartTotal",
      "sendBtn": "cartSend",
      "clearCartBtn": "cartClearAll",
      "popupClose": "popupClose",
      "popupAdd": "popupAdd",
      "i18n-ok-title": "okTitle",
      "againBtn": "againBtn",
    };
    Object.keys(htmlIds).forEach(function (id) {
      var el = document.getElementById(id);
      if (!el) return;
      var val = t(htmlIds[id]);
      if (htmlIds[id].indexOf("guide") === 0 || htmlIds[id].indexOf("coach") === 0) el.innerHTML = val;
      else el.textContent = val;
    });
    var note = document.getElementById("noteInp");
    if (note) note.placeholder = t("notePh");
    var search = document.getElementById("menuSearch");
    if (search) search.placeholder = t("menuSearch");
    if (typeof global.__zekiqOnGuestLang === "function") global.__zekiqOnGuestLang(lang);
  }

  global.__zekiqGuestT = t;
  global.guestT = t;
  global.applyGuestLanguage = apply;
  global.__zekiqGuestLang = lang;
})(window);
